[[headers]]
  for = "/stations.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"